# Default settings notification delivery services.  You can override
# connection settings for one or more environments by creating a
# config/priv/delivery.yml file following the same format as this file.

development:
  delivery_providers:
    sms: dummy
    ivr: dummy

  nexmo:
    #class: Delivery::Provider::Nexmo
    json_endpoint: http://rest.nexmo.com/sms/json
    api_key: ~
    api_secret: ~

  intellivr:
    api_key: ~ # secret API key from INTELLIVR admin interface
    base_url: ~ # URL to INTELLIVR API (i.e. http://HOSTNAME/intellivr/api/api.php)
    callback_url: ~ # URL to have INTELLIVR contact for delivery confirmations

test:
  delivery_providers:
    sms: dummy
    ivr: dummy

production:
  delivery_providers:
    sms: nexmo
    ivr: intellivr

  nexmo:
    json_endpoint: http://rest.nexmo.com/sms/json
    api_key: ~
    api_secret: ~

  intellivr:
    api_key: ~
    base_url: ~
    callback_url: ~

<% file = Rails.root.join('config', 'priv', 'delivery.yml') %>
<%= file.read if file.exist? %>
